"""empty message

Revision ID: 1a29996d7526
Revises: None
Create Date: 2021-02-04 09:00:41.265193

"""

# revision identifiers, used by Alembic.
revision = '1a29996d7526'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
