"""empty message

Revision ID: 944b6c1a3984
Revises: 1a29996d7526
Create Date: 2021-02-23 08:37:19.731910

"""

# revision identifiers, used by Alembic.
revision = '944b6c1a3984'
down_revision = '1a29996d7526'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('code_auth',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('site',
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('ems_id', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('line',
    sa.Column('line_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=True),
    sa.Column('line_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line')
    op.drop_table('site')
    op.drop_table('code_auth')
    op.drop_table('account')
    # ### end Alembic commands ###
